/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class droid_internal_os_ZygoteSocketServer */

#ifndef _Included_droid_internal_os_ZygoteSocketServer
#define _Included_droid_internal_os_ZygoteSocketServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     droid_internal_os_ZygoteSocketServer
 * Method:    nativeIsOpen
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_droid_internal_os_ZygoteSocketServer_nativeIsOpen
  (JNIEnv *, jclass);

/*
 * Class:     droid_internal_os_ZygoteSocketServer
 * Method:    nativeOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_droid_internal_os_ZygoteSocketServer_nativeOpen
  (JNIEnv *, jclass);

/*
 * Class:     droid_internal_os_ZygoteSocketServer
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_droid_internal_os_ZygoteSocketServer_nativeClose
  (JNIEnv *, jclass);

/*
 * Class:     droid_internal_os_ZygoteSocketServer
 * Method:    nativeSetOnReceiveCallback
 * Signature: (Ldroid/internal/os/ZygoteSocketServer/Receiver;)V
 */
JNIEXPORT void JNICALL Java_droid_internal_os_ZygoteSocketServer_nativeSetOnReceiveCallback
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
