/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class droid_internal_os_ZygoteSocketClient */

#ifndef _Included_droid_internal_os_ZygoteSocketClient
#define _Included_droid_internal_os_ZygoteSocketClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     droid_internal_os_ZygoteSocketClient
 * Method:    nativeIsOpen
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_droid_internal_os_ZygoteSocketClient_nativeIsOpen
  (JNIEnv *, jclass);

/*
 * Class:     droid_internal_os_ZygoteSocketClient
 * Method:    nativeOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_droid_internal_os_ZygoteSocketClient_nativeOpen
  (JNIEnv *, jclass);

/*
 * Class:     droid_internal_os_ZygoteSocketClient
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_droid_internal_os_ZygoteSocketClient_nativeClose
  (JNIEnv *, jclass);

/*
 * Class:     droid_internal_os_ZygoteSocketClient
 * Method:    nativeSendMessage
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_droid_internal_os_ZygoteSocketClient_nativeSendMessage
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
