/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class droid_internal_os_ZygoteSocketServer_Receiver */

#ifndef _Included_droid_internal_os_ZygoteSocketServer_Receiver
#define _Included_droid_internal_os_ZygoteSocketServer_Receiver
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
