/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class droid_utils_Log */
#include <iostream>
#include <cstring>

#ifndef _Included_droid_utils_Log
#define _Included_droid_utils_Log
#ifdef __cplusplus
extern "C" {
#endif
#undef droid_utils_Log_LOG_ID_MAIN
#define droid_utils_Log_LOG_ID_MAIN 0L
#undef droid_utils_Log_LOG_ID_RADIO
#define droid_utils_Log_LOG_ID_RADIO 1L
#undef droid_utils_Log_LOG_ID_EVENTS
#define droid_utils_Log_LOG_ID_EVENTS 2L
#undef droid_utils_Log_LOG_ID_SYSTEM
#define droid_utils_Log_LOG_ID_SYSTEM 3L
#undef droid_utils_Log_LOG_ID_CRASH
#define droid_utils_Log_LOG_ID_CRASH 4L
#undef droid_utils_Log_VERBOSE
#define droid_utils_Log_VERBOSE 2L
#undef droid_utils_Log_DEBUG
#define droid_utils_Log_DEBUG 3L
#undef droid_utils_Log_INFO
#define droid_utils_Log_INFO 4L
#undef droid_utils_Log_WARN
#define droid_utils_Log_WARN 5L
#undef droid_utils_Log_ERROR
#define droid_utils_Log_ERROR 6L
#undef droid_utils_Log_ASSERT
#define droid_utils_Log_ASSERT 7L
/*
 * Class:     droid_utils_Log
 * Method:    println_native
 * Signature: (IILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_droid_utils_Log_println_1native
  (JNIEnv *, jclass, jint, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
